### ISSUE TITLE
Reading beam files

### ISSUE THREAD

**Issue by Sebokolodi** [ska-sa/meqtrees-cattery#27]
I'm getting an error which I wasn't previously getting, it has to do with pipeline reading the beam files. Below is the error I'm getting, but from the first paragraph below it shows that the beam files are read properly from their directory `pybeams_fits.filename_pattern=beams/vla_L_$(xy)_$(reim).fits` as specified  BUT somehow when it decomposes them into individual beams it reads them as `beams/vla_L_rr_re.fits`. 

```
2015/06/15 11:58:47 PYXIS: executing '/usr/bin/time meqtree-pipeliner.py --mt 8 -c tdlconf.profiles
 [sim:lsm] ms_sel.msname=applied_soucery000.MS ms_sel.ddid_index=0 ms_sel.field_index=0 
tiggerlsm.filename=test_eish/plots-applied_soucery000/applied_soucery000_recentred-sky.lsm.html 
noise_stddev=0.00766811580507 pybeams_fits.filename_pattern=beams/vla_L_$(xy)_$(reim).fits 
ms_sel.output_column=DATA /home/sebokolodi/builds/meqtrees-cattery/Cattery/Siamese/turbo-sim.py 
=_tdl_job_1_simulate_MS':


  File "/home/sebokolodi/builds/meqtrees-cattery/Cattery/Siamese/OMS/pybeams_fits.py", line 108, in 
make_beam_node

    raise RuntimeError,"Can't find beam pattern file %s"%f;

RuntimeError: Can't find beam pattern file beams/vla_L_rr_re.fits
```

**Comment by o-smirnov** [comment]
Yeah that's due to a bug that's been fixed. $(xy) is meant to stand for the correlation index, which for the JVLA is rr, rl, lr, ll (left- and right-polarized feeds) rather than xx, xy, yx, yy (linearly polarized feeds). In the past it was using the xy designations throughout, but this was in error. 

Just make symlinks so it can find the beams at the new filenames:

```
$ cd beams
$ ln -s vla_L_xx_re.fits vla_L_xx_re.fits
# ... etc. for the other 7 files, linking x to r and y to l.
```

**Comment by modhurita** [comment]
I think @o-smirnov meant the 2nd line above to be:

```
$ ln -s vla_L_xx_re.fits vla_L_rr_re.fits
```

However, I think the [correspondence](https://github.com/ratt-ru/calibration-pipelines/issues/34#issuecomment-103432446) should be x->l and y->r.

@Sebokolodi, if you are working with real data, I think you should start using the newest simulated beam files - you can find the fits files at `elwood: /home/mitra/PrimaryBeamReduction/JVLA-L-{rr,rl,lr,ll}_{re,im}.fits`.

**Comment by o-smirnov** [comment]
No, x->r and y->l. We had double confusion due to the coordinate system being mirrored, but we worked it all out: https://github.com/ratt-ru/beam-me-up/issues/3#issuecomment-103791787

But in any case I agree, just grab the correctly-named beams that @modhurita hs pointed you to, and don't worry about the filenames anymore.

**Comment by Sebokolodi** [comment]
Thanks
